[tool.poetry]
name = "tiktokmassbotting"
version = "0.1.0"
description = ""
authors = ["Cyxee <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pystyle = "^1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
